version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8080:15672"
    volumes:
      - rmq-data:/var/lib/rabbitmq


  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"


volumes:
  rmq-data: