# Generated by Django 4.2.2 on 2023-06-27 09:38

from django.db import migrations

CATEGORY_NAME = "default"


def forward_func(apps, schema_editor):
    Category = apps.get_model("shop", "Category")
    db_alias = schema_editor.connection.alias
    Category.objects.using(db_alias).create(name=CATEGORY_NAME, description="default category",)


def reverse_func(apps, schema_editor):
    Category = apps.get_model("shop", "Category")
    db_alias = schema_editor.connection.alias
    Category.objects.using(db_alias).filter(name=CATEGORY_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_category'),
    ]

    operations = [
        migrations.RunPython(
            code=forward_func,
            reverse_code=reverse_func,
        ),
    ]
