# Generated by Django 4.2.3 on 2023-07-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderpaymantdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpaymantdetails',
            options={'verbose_name_plural': 'Order Payment Details'},
        ),
        migrations.AlterField(
            model_name='orderpaymantdetails',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='shop.order'),
        ),
    ]
