"""Users add colum bio

Revision ID: 313eebfbbd74
Revises: 7f37d03981ae
Create Date: 2023-06-23 22:57:24.522540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "313eebfbbd74"
down_revision = "7f37d03981ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blog_users", sa.Column("bio", sa.String(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "bio")
    # ### end Alembic commands ###
