"""Users remove colum bio

Revision ID: 15c047dbf4d2
Revises: 49da3b0dd588
Create Date: 2023-06-23 23:23:07.148120

"""
from alembic import op
import sqlalchemy as sa
from models import Author, User

# revision identifiers, used by Alembic.
revision = "15c047dbf4d2"
down_revision = "49da3b0dd588"
branch_labels = None
depends_on = None

metadata = sa.MetaData()


users_table = sa.Table(
    "blog_users",
    metadata,
    sa.Column("id", sa.Integer),
    sa.Column("bio", sa.VARCHAR())

)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "bio")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column(
            "bio",
            sa.VARCHAR(),
            # server_default=sa.text("''::character varying"),
            # autoincrement=False,
            # nullable=False,
        ),
    )
    bind = op.get_bind()
    bind.execute(
        sa.update(users_table)
        .where(Author.user_id == users_table.c.id)
        .values({users_table.c.bio: Author.bio})
    )
    # ### end Alembic commands ###
