"""Create table post_tags_association

Revision ID: 3481475af29f
Revises: 3ecb4939deeb
Create Date: 2023-06-26 11:37:29.731032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3481475af29f"
down_revision = "3ecb4939deeb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_post_tags_association",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["blog_posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["blog_tags.id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blog_post_tags_association")
    # ### end Alembic commands ###
